name: fusion_xfeat_sfd2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.*
  - torchvision=0.16.*
  - torchaudio=2.1.*
  - pytorch-cuda=12.1
  - pip
  - numpy=1.24.*
  - scipy=1.11.*
  - scikit-learn=1.3.*
  - scikit-image=0.21.*
  - opencv=4.8.*
  - Pillow=10.*
  - kornia=0.7.1
  - matplotlib=3.8.*
  - seaborn=0.13.*
  - pandas=2.1.*
  - h5py=3.9.*
  - yaml
  - tqdm
  - pip:
      - albumentations==1.4.3
      - imageio==2.34.0
      - imgaug==0.4.0
      - wandb==0.17.0
      - tensorboard==2.16.2
      - jsonschema==4.22.0
      - trimesh==4.4.0
      - pytorch3d==0.7.6
      - lmdb==1.4.1
      - joblib==1.4.2
      - multiprocess==0.70.16
      - onnx==1.16.1
      - onnxruntime==1.18.0
      - torch-quantization==2.1.2
      - black==24.4.2
      - isort==5.13.2
      - flake8==7.0.0
      - sphinx==7.3.7
      - sphinx-rtd-theme==2.0.0
      - typing-extensions==4.12.0
      - rich==13.7.1
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - yapf==0.40.2
